### ISSUE TITLE
Reflection of our project

### ISSUE THREAD

**Issue by qiaoyue211** [Shin-Huang/Local-Peace-Agreement#10]
Please leave some comments of our work towards peace agreements, especially the reflection part, thus I can put it into report.

**Comment by TerryQu1997** [comment]
I think we can add some planning for the future in the reflection section.
We will add some conflict data in the future so that our users can more clearly compare the number and distribution of local peace agreements with local conflicts. Second, our analysis is focused on the Middle East, so there is a lack of regional news and analysis on the site. Finally, we want to add a search function that allows users to search whatever they want in our database.
