### ISSUE TITLE
group 13 presentation

### ISSUE THREAD

**Issue by Dora-wang777** [Shin-Huang/Local-Peace-Agreement#6]
[group13 slides.pptx](https://github.com/Shin-Huang/Local-Peace-Agreement/files/5641637/group13.slides.pptx)

**Comment by Dora-wang777** [comment]
Do you have any suggestions about our slides？

**Comment by Shin-Huang** [comment]
On Page 4, I would try to adjust the layout of the content of the sub-title, **Conclusion** and move "We found some interesting results" onto the top of the four bullet point. (Please see the image I attached within this comment)
![1](https://user-images.githubusercontent.com/53304481/101218187-862df180-367a-11eb-9bff-351723702b7f.JPG)

**Comment by Shin-Huang** [comment]
In addition, we will need to replace the two graphs based off my analysis report on page 10 and 11 because the data were not clean. I have uploaded the correct ones onto Github but just in case if you cannot find them, I'm attaching them within this comment as well:

![LatitudeContries](https://user-images.githubusercontent.com/53304481/101218398-ea50b580-367a-11eb-84b3-fe1b5e70bf38.png)
![LongitudeContries](https://user-images.githubusercontent.com/53304481/101218400-eae94c00-367a-11eb-8751-c98411561427.png)

**Comment by Dora-wang777** [comment]
@Shin-Huang thank you for your suggestions, I will try to modify them.

**Comment by Shin-Huang** [comment]
Can you update the current content with us and if there's no more adjustments, I'll close this issue. Thank you, Wang.
